### PR TITLE
Remove unexpected :slug error on valid model, fixes #949

### LINKED ISSUE #949: Unexpected :slug error on valid, unpersisted model
While testing friendly_id 5.4.0, we are seeing something that is odd (I think -- I may be misunderstanding).

After constructing (but not saving) an instance (let's call it `my_instance`) of a given MyModel that uses `friendly_id :some_method, use: [:slugged, :finders]`, we see that while `my_instance.valid?` is `true`, `my_instance.errors.messages` is `{:slug=>[]}`.

Is this intentional? I find it rather peculiar, but I cannot pretend to be an expert here or fully understand what's going on under the hood with friendly_id. I am happy to flesh out this example if desired -- just let me know what extra info, if any, would be helpful!

### PR DESCRIPTION
**Pull request by caiofilipemr**
I believe this simple change solves the _issue_ #949.

### CODE REVIEW

**Comment by parndt** [comment]
Thanks @caiofilipemr that looks like it could do the trick, but CI is failing for this change?

**Comment by giovannibonetti** [comment]
Hi, @parndt! I work with @caiofilipemr and we were looking into this together.

> but CI is failing for this change?

After [taking a closer look](https://github.com/norman/friendly_id/pull/952/checks?check_run_id=1036629354) it seems like the few cases that failed are not related to these changes at all:

image

Can you run the tests again? It seems like the Coveralls configuration is a bit unstable.

**Comment by parndt** [comment]
> After [taking a closer look](https://github.com/norman/friendly_id/pull/952/checks?check_run_id=1036629354) it seems like the few cases that failed are not related to these changes at all:

it also reports this failure: https://github.com/norman/friendly_id/pull/952/checks?check_run_id=1036629235#step:10:99

I'll re-run and see. It's failing on Rails 5.0 tests which leads me to believe it's related to Rails 5.

**Comment by parndt** [comment]
> It seems like the Coveralls configuration is a bit unstable.

Sometimes I wonder if it's even a worthwhile measurement. 😄

**Comment by parndt** [comment]
Rather than fight CI, I've opened #954

**Comment by parndt** [comment]
@caiofilipemr can you pull in the latest changes to your branch please so that CI may pass?

**Comment by parndt** [comment]
Thanks!

**Pull request merged**
