### PR TITLE
Bug 744: Support scoped with STI

### PR DESCRIPTION
**Pull request by mpasad**

### CODE REVIEW

**Comment by jheth** [comment]
This is blocking us right now.  @norman what do you think?

**Comment by ncphillips** [comment]
This is also blocking us @norman

**Comment by jpatters** [comment]
is there a reason this hasn't been fixed/merged? It seems to fix the issue
/cc @parndt

**Comment by parndt** [comment]
I've triggered a build based on the latest code: https://travis-ci.org/norman/friendly_id/builds/408779856

**Pull request merged**
