### PR TITLE
fix temp generators solution for Rails 5.1+

### PR DESCRIPTION
**Pull request by zhisme**
Hey there.

I fixed your temp solution for Rails 5 migration templates. And it seems more elegant now.
Also it would be nice if we can get rid of this migration object, because it's seems like hack to me, that generator template were used across tests as a real object. That's why I moved it to migration_mock.rb
Anyway I'm ready to talk. :)

### CODE REVIEW

**Comment by zhisme** [comment]
seems like CI configuration were broken long ago.

**Comment by zhisme** [comment]
@jrochkind yeah, they have temp fix in readme. 
I tried to use more generic working solution the rails way.

Temp solution for Rails 5.1+ : Before running the migration, go into the generated migration file and specify the Rails version:
```
class CreateFriendlyIdSlugs < ActiveRecord::Migration[5.1]
```

**Comment by jrochkind** [comment]
@zhisme is nothing past the "temp fix" planned? The temp fix is a problem in some CI contexts where CI is trying to build an app with friendly id in an automated fashion.

**Comment by zhisme** [comment]
@jrochkind I cannot tell you. But nothing tell us that they are gonna do something more than temp fix.

**Comment by parndt** [comment]
One problem is that this code causes the test suite to fail - check out [this build job](https://travis-ci.org/norman/friendly_id/jobs/350377478#L961) for example. The same thing happens for me locally.

```
➜  friendly_id git:(fb3260e) bundle exec rake
~/.rubies/ruby-2.4.2/bin/ruby -w -I"lib:test" -I"~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib" "~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb" "test/base_test.rb" "test/candidates_test.rb" "test/configuration_test.rb" "test/core_test.rb" "test/finders_test.rb" "test/generator_test.rb" "test/history_test.rb" "test/object_utils_test.rb" "test/reserved_test.rb" "test/scoped_test.rb" "test/sequentially_slugged_test.rb" "test/simple_i18n_test.rb" "test/slugged_test.rb" "test/sti_test.rb"
~/.gem/ruby/2.4.2/gems/activesupport-4.2.10/lib/active_support/core_ext/enumerable.rb:20: warning: method redefined; discarding old sum
-- [](4.2)
~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection': No connection pool for ActiveRecord::Base (ActiveRecord::ConnectionNotEstablished)
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:648:in `connection'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:664:in `block in method_missing'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
	from ~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:416:in `method_missing'
	from ~/code/parndt/friendly_id/test/migration_mock.rb:1:in `<top (required)>'
	from ~/code/parndt/friendly_id/test/schema.rb:1:in `require'
	from ~/code/parndt/friendly_id/test/schema.rb:1:in `<top (required)>'
	from ~/code/parndt/friendly_id/test/helper.rb:109:in `require'
	from ~/code/parndt/friendly_id/test/helper.rb:109:in `<top (required)>'
	from ~/code/parndt/friendly_id/test/base_test.rb:1:in `require'
	from ~/code/parndt/friendly_id/test/base_test.rb:1:in `<top (required)>'
	from ~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb:17:in `require'
	from ~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from ~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb:5:in `select'
	from ~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib" "~/.gem/ruby/2.4.2/gems/rake-12.1.0/lib/rake/rake_test_loader.rb" "test/base_test.rb" "test/candidates_test.rb" "test/configuration_test.rb" "test/core_test.rb" "test/finders_test.rb" "test/generator_test.rb" "test/history_test.rb" "test/object_utils_test.rb" "test/reserved_test.rb" "test/scoped_test.rb" "test/sequentially_slugged_test.rb" "test/simple_i18n_test.rb" "test/slugged_test.rb" "test/sti_test.rb" ]
~/.gem/ruby/2.4.2/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
~/.gem/ruby/2.4.2/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
~/.gem/ruby/2.4.2/bin/bundle:23:in `load'
~/.gem/ruby/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by zhisme** [comment]
@parndt looking into your issues 
```
~/.gem/ruby/2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection': No connection pool for ActiveRecord::Base (ActiveRecord::ConnectionNotEstablished)
```
I don't think this relates somehow to PR. This issue with connection pool were before I created this PR. I think you should restart build on CI, cause I just checked it locally and I got success.

```bash
bundle exec rake

Finished in 3.042788s, 141.9751 runs/s, 249.4423 assertions/s.
432 runs, 759 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by parndt** [comment]
Ah @zhisme I think you're right that this got fixed by another commit as part of #849

Thank you for your help!  I'd still welcome your feedback about how this code could be improved further?

**Comment by zhisme** [comment]
@parndt Yeah, let's see when they release rails 6.0 :)
Thank you for the gem!

**Pull request closed without merging**
