### PR TITLE
Fix slug for composite primary keys

### PR DESCRIPTION
**Pull request by lordmortis**
I'd like to add tests and anything else you need to get this merged? (This increases compatibility with [Composite Primary Keys](https://github.com/composite-primary-keys/composite_primary_keys))

### CODE REVIEW

**Comment by parndt** [comment]
I wonder if composite key support could be built as a plugin instead, to avoid all this conditional logic. For example:

```ruby
friendly_id :title, use: [:slugged, :composite_key]
```

**Comment by lordmortis** [comment]
@parndt would that make testing easier? I kind-of-like the "just works" approach, although you do have to be careful about your include ordering to get friendly Id and CompositePrimaryKeys working together (because they both override the param method)

**Comment by parndt** [comment]
No, I just think the patch is quite verbose and makes the code more difficult to understand. The fact that it's repeated for scoped and slugged makes me think it should be its own thing.

**Comment by norman** [comment]
I'd prefer not to include this - if this were intended to support a feature that's in Active Record then it would be fine, but I don't think the core of FriendlyId should include support for 3rd libraries. That should go in its own module as @parndt suggested. This is the approach we've taken with Globalize, where friendyld_id-globalize is its own gem.

However if there are modifications needed to make FriendlyId easier to extend and make such a module/gem possible, then I'd be happy to add that. Perhaps the various modules need to provide a `primary_key_scope` method that can be overridden where necessary.

**Comment by lordmortis** [comment]
[Here](/lordmortis/friendly_id-composite_primary_keys) <- that's my first pass at the plugin (which is basically just overriding the scope_for_slug_generator like my patch did. 

primary_key_scope would likely make this a lot easier to do, and i'll look at that when i get some more time. For now, if anyone is looking to use friendly_id with composite_primary_key - there's now a plugin! (not sure if there's a place these get listed?)

**Pull request closed without merging**
